/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import modelo.Personagem;

/**
 *
 * @author Lucas
 */
public class ViewConquistas extends javax.swing.JDialog {
   Personagem personagem;

    /**
     * Creates new form ViewConquistas
     */
    public ViewConquistas(java.awt.Frame parent, boolean modal, Personagem personagem) {
        super(parent, modal);
        initComponents();
        this.personagem = personagem;
        lblVitorias10.setText(personagem.getVitorias() + "/10");
        lblVitorias30.setText(personagem.getVitorias() + "/30");
        lblVitorias50.setText(personagem.getVitorias() + "/50");
        this.getContentPane().setBackground(ViewPersonagem.pegaCor()); 
        
        if (personagem.getVitorias() >=10) {
          lblMedalha10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/10vitorias.png")));
        } else {
          lblMedalha10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/10vitoriasp.png")));
        }
        
         if (personagem.getVitorias() >=30) {
          lblMedalha30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/30vitorias.png")));
        } else {
          lblMedalha30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/30vitoriasp.png")));
        }
         
          if (personagem.getVitorias() >=50) {
          lblMedalha50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/50vitorias.png")));
        } else {
          lblMedalha50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/50vitoriasp.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMedalha50 = new javax.swing.JLabel();
        lblMedalha10 = new javax.swing.JLabel();
        lblMedalha30 = new javax.swing.JLabel();
        lblAmeacador = new javax.swing.JLabel();
        lblImortal = new javax.swing.JLabel();
        lblVingativo = new javax.swing.JLabel();
        lblProgresso30 = new javax.swing.JLabel();
        lblProgresso50 = new javax.swing.JLabel();
        lblProgresso10 = new javax.swing.JLabel();
        lblVitorias30 = new javax.swing.JLabel();
        lblVitorias10 = new javax.swing.JLabel();
        lblVitorias50 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Conquistas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conquistas");

        lblMedalha50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMedalha10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMedalha30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblAmeacador.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAmeacador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmeacador.setText("Ameaçador - 10 vitórias");

        lblImortal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblImortal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblImortal.setText("Imortal - 50 vitórias");

        lblVingativo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblVingativo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVingativo.setText("Vingativo - 30 vitórias");

        lblProgresso30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProgresso30.setText("Progresso:");

        lblProgresso50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProgresso50.setText("Progresso:");

        lblProgresso10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProgresso10.setText("Progresso:");

        lblVitorias30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblVitorias10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblVitorias50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMedalha10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedalha30, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedalha50, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmeacador, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVingativo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblProgresso30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVitorias30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProgresso50, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVitorias50, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblImortal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblProgresso10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVitorias10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAmeacador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProgresso10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVitorias10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblMedalha10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedalha30)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVingativo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProgresso30)
                            .addComponent(lblVitorias30, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedalha50)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImortal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProgresso50)
                            .addComponent(lblVitorias50, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConquistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConquistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConquistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConquistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewConquistas dialog = new ViewConquistas(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAmeacador;
    private javax.swing.JLabel lblImortal;
    private javax.swing.JLabel lblMedalha10;
    private javax.swing.JLabel lblMedalha30;
    private javax.swing.JLabel lblMedalha50;
    private javax.swing.JLabel lblProgresso10;
    private javax.swing.JLabel lblProgresso30;
    private javax.swing.JLabel lblProgresso50;
    private javax.swing.JLabel lblVingativo;
    private javax.swing.JLabel lblVitorias10;
    private javax.swing.JLabel lblVitorias30;
    private javax.swing.JLabel lblVitorias50;
    // End of variables declaration//GEN-END:variables
}
