/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ferramentas.CaixaDeDialogo;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import modelo.Oponente;
import modelo.Personagem;

/**
 *
 * @author lucas.pandolfo
 */
public class ViewConfronto extends javax.swing.JFrame {
   Personagem personagem;
   Oponente oponente = new Oponente();
   Random gerador = new Random();
   public static int ataque = 0;
   public static int ataqueO = 0;
   public static Timer tempo;

    /**
     * Creates new form ViewConfronto
     */
    public ViewConfronto(Personagem personagemEscolhido) throws IOException {
        initComponents();
        limparLabels();
        this.personagem = personagemEscolhido;
        
        mostrarPersonagem(); //Preenche os dados do personagem
        gerarOponente(); // Gera um novo oponente
        mostrarOponente(); //Preenche os dados do oponente;
        lblImagemP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/"+personagem.getClasse().toLowerCase()+".png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeP = new javax.swing.JLabel();
        lblAtaqueP = new javax.swing.JLabel();
        lblVidaP = new javax.swing.JLabel();
        txtNomeP = new javax.swing.JLabel();
        txtAtaqueP = new javax.swing.JLabel();
        txtVidaP = new javax.swing.JLabel();
        lblClasseP = new javax.swing.JLabel();
        txtClasseP = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblBatalha = new javax.swing.JLabel();
        lblNivelP = new javax.swing.JLabel();
        txtNivelP = new javax.swing.JLabel();
        lblAtaqueB = new javax.swing.JLabel();
        lblVidaB = new javax.swing.JLabel();
        txtNomeB = new javax.swing.JLabel();
        txtAtaqueB = new javax.swing.JLabel();
        txtVidaB = new javax.swing.JLabel();
        lblNomeB = new javax.swing.JLabel();
        btnAtacar = new javax.swing.JButton();
        lblAtaqueDe = new javax.swing.JLabel();
        lblAtkPersonagem = new javax.swing.JLabel();
        lblAtkOponente = new javax.swing.JLabel();
        lblVezOponente = new javax.swing.JLabel();
        lblVezPersonagem = new javax.swing.JLabel();
        txtDescB = new javax.swing.JLabel();
        lblImagemB = new javax.swing.JLabel();
        lblImagemP = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNomeP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNomeP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/usuario.png"))); // NOI18N
        lblNomeP.setText("Nome:");

        lblAtaqueP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAtaqueP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ataque.png"))); // NOI18N
        lblAtaqueP.setText("Ataque:");

        lblVidaP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVidaP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/coracao.png"))); // NOI18N
        lblVidaP.setText("Vida:");

        txtNomeP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtAtaqueP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtVidaP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblClasseP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClasseP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/classe.png"))); // NOI18N
        lblClasseP.setText("Classe:");

        txtClasseP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblBatalha.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lblBatalha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBatalha.setText("Campo de Batalha");

        lblNivelP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNivelP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/nivel.png"))); // NOI18N
        lblNivelP.setText("Nível:");

        txtNivelP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblAtaqueB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAtaqueB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ataque.png"))); // NOI18N
        lblAtaqueB.setText("Ataque:");

        lblVidaB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVidaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/coracao.png"))); // NOI18N
        lblVidaB.setText("Vida:");

        txtNomeB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtAtaqueB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtVidaB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblNomeB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNomeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/boss.png"))); // NOI18N
        lblNomeB.setText("Nome:");

        btnAtacar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtacar.setText("Atacar");
        btnAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacarActionPerformed(evt);
            }
        });

        lblAtkPersonagem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblAtkPersonagem.setText("Ataque do Personagem");

        lblAtkOponente.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblAtkOponente.setText("Ataque do Oponente");

        lblVezOponente.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblVezOponente.setText("Vez de seu oponente atacar");

        lblVezPersonagem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblVezPersonagem.setText("Sua vez de atacar");

        txtDescB.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtDescB.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensagem:"));

        lblX.setFont(new java.awt.Font("Tahoma", 1, 140)); // NOI18N
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBatalha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAtkPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVezPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAtaqueDe, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAtkOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVezOponente, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAtacar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVidaB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtVidaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAtaqueB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAtaqueB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNomeB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomeB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVidaP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtVidaP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAtaqueP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAtaqueP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNivelP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNivelP, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblClasseP)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtClasseP, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblNomeP)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImagemP, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lblImagemB, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescB, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jSeparator1)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblBatalha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeP)
                            .addComponent(txtNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClasseP)
                            .addComponent(txtClasseP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNivelP)
                            .addComponent(txtNivelP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAtaqueP)
                            .addComponent(txtAtaqueP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVidaP)
                            .addComponent(txtVidaP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNomeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNomeB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAtaqueB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAtaqueB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVidaB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVidaB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblImagemB, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagemP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAtaqueDe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVezOponente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtkOponente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVezPersonagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtkPersonagem)))
                .addGap(204, 204, 204)
                .addComponent(btnAtacar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarActionPerformed
        // TODO add your handling code here
        int valorDado = gerador.nextInt(2) + 1;
        if (valorDado == 1) {
        System.out.println("Ataque do seu personagem: " + valorDado);
        lblVezPersonagem.setText("Sua Vez de Atacar");  
        lblVezOponente.setText("");
        lblAtkOponente.setText("");
        ataquePersonagem();
         } else {
        System.out.println("Ataque do seu oponente: "  + valorDado);
        lblVezOponente.setText("É a vez de seu oponente atacar"); 
        lblVezPersonagem.setText("");
        lblAtkPersonagem.setText("");
        ataqueOponente();
        }
        
        //Valida se o oponente já morreu e gera um novo para lutar.
        if (oponente.getVida() > 0) {
        mostrarOponente();
        } else {
        mostrarOponente();
        CaixaDeDialogo.obterinstancia().exibirMensagem("Parabéns, você derrotou o oponente " + oponente.getNome() + "\nVocê ganhou 100 de vida.","Atenção",'i');
        aumentaVida(); 
        gerarOponente();
        mostrarOponente();
        
        if (personagem.getVida() < 100) {
        boolean wResposta = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Atenção sua vida está abaixo de 100\nDeseja continuar lutando?","Vida",'p');         
        if (wResposta == true) {
        gerarOponente();
        limparLabels();
        mostrarOponente();
        } else {
            limparLabels();
            return;
         }
        }
        }
       
        //Valida se o personagem não ficou sem vida
         if (personagem.getVida() > 0) {
         mostrarPersonagem();
         } else {
         mostrarPersonagem();
         CaixaDeDialogo.obterinstancia().exibirMensagem("Você foi derrotado!\nEsperamos que você esteja mais forte na próxima luta. " + oponente.getNome(),"GAME OVER",'i');
         ViewPersonagem tela = new ViewPersonagem();
         tela.setVisible(true);
         this.setVisible(false);
         } 
      
// barra de vida progresso
// array de oponentes
   
    }//GEN-LAST:event_btnAtacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConfronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConfronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConfronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConfronto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewConfronto(null).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ViewConfronto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private Oponente gerarOponente () {
    try {    
    // +1 não deixa gerar 0
    int numero = gerador.nextInt(5) + 1;
    
    if (numero == 1) {
        oponente.setNome("Mandala");
        oponente.setVida(600);
        oponente.setAtaque(200);  
        oponente.setDescricao("<html> Será que você consegue derrpotar o Rei dos macacos? <br> por: " + oponente.getNome() + "</html>");
   lblImagemB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/"+oponente.getNome().toLowerCase()+".gif")));
    }
    else if (numero == 2) {
        oponente.setNome("Rei Trator");
        oponente.setVida(300);
        oponente.setAtaque(150);    
        oponente.setDescricao("<html> Preparado para perder? <br> por: " + oponente.getNome() + "</html>");
   lblImagemB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/"+oponente.getNome().toLowerCase()+".gif")));
    }
      else if (numero == 3) {
        oponente.setNome("Corcel do Inferno");
        oponente.setVida(800);
        oponente.setAtaque(300);    
        oponente.setDescricao("<html> Demonstre sua força para mim. <br> por: " + oponente.getNome()+ "</html>");
   lblImagemB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/"+oponente.getNome().toLowerCase()+".gif")));
      }
      else if (numero == 4) {
        oponente.setNome("Lorden");
        oponente.setVida(400);
        oponente.setAtaque(200);    
        oponente.setDescricao("<html> Espero que esteja preparado para a glória! <br> por: " + oponente.getNome()+ "</html>");
   lblImagemB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/"+oponente.getNome().toLowerCase()+".gif")));
      }
      else if (numero == 5) {
        oponente.setNome("Louva-Deus");
        oponente.setVida(500);
        oponente.setAtaque(300);    
        oponente.setDescricao("<html> Cuidado por onde andas! <br> por: " + oponente.getNome()+"</html>");
        lblImagemB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personagens/"+oponente.getNome().toLowerCase()+".gif")));
      }
        return oponente;
    
    } catch (Exception e) {
        CaixaDeDialogo.obterinstancia().exibirMensagem(e.getMessage().toString(),"ERRO",'e');
        return null;
    }
    }
    
    private void mostrarPersonagem() {
        txtNomeP.setText(personagem.getNome());
        txtClasseP.setText(personagem.getClasse());
        txtNivelP.setText(String.valueOf(personagem.getNivel()));
        txtAtaqueP.setText(String.valueOf(personagem.getAtaque()));
        txtVidaP.setText(String.valueOf(personagem.getVida()));
    }
    
    private void mostrarOponente() {
         //Preenche o Oponente
        txtNomeB.setText(oponente.getNome());
        txtAtaqueB.setText(String.valueOf(oponente.getAtaque()));
        txtVidaB.setText(String.valueOf(oponente.getVida()));
        txtDescB.setText(oponente.getDescricao());
    }
    
    private void ataquePersonagem() {
        //Personagem ataca o oponente
       int valorDado = gerador.nextInt(20) + 1;
        if (valorDado > 13) { //Ataque Critico 
           ataque = personagem.getAtaque() / 2;
        } else {
            ataque = personagem.getAtaque() / 3;
        }
        System.out.println("DADO = " + valorDado);
        System.out.println("Ataque = " + ataque);
        
        //Vez do ataque e tempo    
        lblAtkPersonagem.setText("Aguarde o ataque");
        tempo = new Timer(400, new ActionListener() {//vai esperar 5 segundos e executar essa ação
        @Override
        public void actionPerformed(ActionEvent e) {
               lblAtkPersonagem.setText("Seu ataque foi de: " + ataque); //removo o conteudo do text, ou remove da tela, faz qualquer coisa
               tempo.stop();//paro a contagem, pra não ser executado de novo
        }
        });
        tempo.start();
        
        int vidaRestante = (oponente.getVida() - ataque);
        System.out.println("Vida restante do Oponente: " + vidaRestante);
        oponente.setVida(vidaRestante);   
  }
    private void ataqueOponente() {
        //Oponente ataca o personagem
        int valorDado = gerador.nextInt(20) + 1;
        if (valorDado > 18) { //Ataque Critico 
            ataque = oponente.getAtaque() / 2;
        } else {
            ataque = oponente.getAtaque() / 4;
        }
        System.out.println("DADO = " + valorDado);
        System.out.println("Ataque = " + ataque);
        
       //Vez do ataque e tempo    
        lblAtkOponente.setText("Aguarde o ataque");
        tempo = new Timer(400, new ActionListener() {//vai esperar 5 segundos e executar essa ação
        @Override
        public void actionPerformed(ActionEvent e) {
               lblAtkOponente.setText("O ataque do seu oponente foi de: " + ataque); //removo o conteudo do text, ou remove da tela, faz qualquer coisa
               tempo.stop();//paro a contagem, pra não ser executado de novo
        }
        });
        tempo.start();

        int vidaRestante = personagem.getVida() - ataque;
        System.out.println("Vida restante do Personagem: " + vidaRestante);
        personagem.setVida(vidaRestante); 
 
 }
    
    public void limparLabels() {
        lblAtkPersonagem.setText("");
        lblAtkOponente.setText("");
        lblVezPersonagem.setText("");
        lblVezOponente.setText("");    
    }
    
    private void aumentaVida() {
        int vida = 100;
        personagem.setVida(personagem.getVida() + vida);
    }

 
    public void imagensBatalha (String img) {
          String diretorio = "/br/com/ProjetoRPG/ProjetoRPG/src/personagens/" + img + ".png";
        try {
            URL resource = getClass().getResource(diretorio);
            File file = new File(resource.toURI());
            //setando o icone
            ImageIcon logo = new ImageIcon(file.getPath());
            lblImagemB.setIcon(logo);  
        } catch (URISyntaxException ex) {
           //algo errado
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAtaqueB;
    private javax.swing.JLabel lblAtaqueDe;
    private javax.swing.JLabel lblAtaqueP;
    private javax.swing.JLabel lblAtkOponente;
    private javax.swing.JLabel lblAtkPersonagem;
    private javax.swing.JLabel lblBatalha;
    private javax.swing.JLabel lblClasseP;
    private javax.swing.JLabel lblImagemB;
    private javax.swing.JLabel lblImagemP;
    private javax.swing.JLabel lblNivelP;
    private javax.swing.JLabel lblNomeB;
    private javax.swing.JLabel lblNomeP;
    private javax.swing.JLabel lblVezOponente;
    private javax.swing.JLabel lblVezPersonagem;
    private javax.swing.JLabel lblVidaB;
    private javax.swing.JLabel lblVidaP;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel txtAtaqueB;
    private javax.swing.JLabel txtAtaqueP;
    private javax.swing.JLabel txtClasseP;
    private javax.swing.JLabel txtDescB;
    private javax.swing.JLabel txtNivelP;
    private javax.swing.JLabel txtNomeB;
    private javax.swing.JLabel txtNomeP;
    private javax.swing.JLabel txtVidaB;
    private javax.swing.JLabel txtVidaP;
    // End of variables declaration//GEN-END:variables
}
